# Generated by tools/compile_chapter1.py from the supplied Chapter 1.
# Dialogue and captions are immutable; presentation and systems live separately.


label chapter_01:
    $ enter_chapter(1)
    # [BG] Phòng trọ / phòng ngủ sinh viên IT. Trời vừa sáng. Rèm cửa hơi hé. Laptop vẫn đang mở, Discord còn hiện ở màn hình. Một lon nước ngọt lăn dưới bàn. (KTXDay.png)
    scene bedroom_morning
    $ scene_ambience("room")
    $ set_stage("player")
    with Dissolve(0.3)
    # [SFX] Chim hót. Lá cây xào xạc. Quạt máy quay “cạch… cạch… cạch…”
    $ play_scene_sound("birds")
    n "Sáng sớm tinh mơ. Chim hót. Lá cây xào xạc.\nMột ngày tốt lành mới bắt đầu cho muôn loài…"
    # [ACT] Camera pan xuống cái giường.
    show bedroom_morning at morning_pan
    n "…ngoại trừ một thằng IT mới ngủ được khoảng bốn tiếng."
    # [BG] Màn hình Discord + game đang chạy.
    scene bedroom_gaming
    $ scene_ambience()
    $ set_stage()
    with Dissolve(0.3)
    show screen device_panel
    with fade
    minh_discord "Ván cuối nha."
    $ set_player_expression("annoyed")
    mc "Mày nói câu đó bốn ván rồi."
    m "Lần này là ván cuối thật."
    mc "Thế sao nút “Find Match” của mày sáng vậy?"
    m "Do game bug."
    $ set_player_expression("smug")
    mc "À. Bug nằm ở ngón tay mày hả?"
    system_msg "Match found."
    m "…vào không?"
    $ set_player_expression("normal")
    mc "Vào."
    system_msg "Một quyết định có trách nhiệm đã được đưa ra."
    hide screen device_panel
    scene bedroom_morning with fade
    $ scene_ambience("room")
    $ set_stage("player")
    # [SFX] RING! RING! RING!
    $ play_scene_sound("alarm")
    # [ACT] MC trở mình, kéo chăn trùm đầu.
    unknown_woman "Xin hãy tỉnh dậy… hỡi người được chọn~~"
    $ set_player_expression("surprised")
    mc "…Cái what the—"
    # [ACT] “Nữ thần” xuất hiện với trượng phép (IngameSystem.png).
    scene dream_place
    $ scene_ambience()
    $ set_stage("player", "necrass")
    with fade
    $ set_player_expression("thinking")
    mc "Khoan… mặt này quen quen."
    $ set_player_expression("surprised")
    mc "Ủa đây chả phải N***** trong game A****** à???"
    goddess "Anh đã lầm."
    $ set_player_expression("deadpan")
    mc "Ờ."
    goddess "Ta chỉ là vợ của tác giả trò chơi này."
    $ set_player_expression("annoyed")
    mc "…Còn tệ hơn cái tôi vừa đoán."
    goddess "Im lặng. Tutorial đang chạy."
    system_msg "SYSTEM ENTITY: NECRASS_SIM.exe"
    necrass_sim "Ngươi là người được chọn."
    $ set_player_expression("confused")
    mc "Được chọn làm gì?"
    necrass_sim "Đi học đúng giờ."
    $ set_player_expression("nervous")
    mc "…Trả tôi về được không, plz~?"
    necrass_sim "Nah."
    necrass_sim "Trong hành trình này, ngươi sẽ phải quản lý một nguồn tài nguyên vô cùng quý giá."
    # [ACT] Thanh ENERGY 60/100 hiện lên.
    $ energy_visible = True
    show screen energy_hud
    $ set_player_expression("thinking")
    mc "Mana?"
    necrass_sim "Không."
    mc "Stamina?"
    necrass_sim "Không."
    mc "Tiền?"
    necrass_sim "Còn quý hơn."
    $ set_player_expression("deadpan")
    mc "…"
    necrass_sim "Sức sống còn sót lại của một sinh viên IT thiếu ngủ."
    system_msg "ENERGY SYSTEM UNLOCKED"
    necrass_sim "Mọi lựa chọn đều có giá của nó. Có lựa chọn khiến ngươi khỏe hơn. Có lựa chọn khiến ngươi mệt hơn."
    $ set_player_expression("smug")
    mc "Có lựa chọn nào cho nghỉ học không?"
    necrass_sim "Có."
    $ set_player_expression("veryhappy")
    mc "Thật á?"
    necrass_sim "Nhưng game sẽ kết thúc ở Chapter 1."
    $ set_player_expression("annoyed")
    mc "Tác giả độc tài vậy?"
    necrass_sim "Ta là vợ tác giả."
    $ set_player_expression("deadpan")
    mc "Ờ quên."
    necrass_sim "Ngoài Energy, một số nhân vật sẽ ghi nhớ cách ngươi cư xử."
    system_msg "Một vài chỉ số quan hệ sẽ không được hiển thị trực tiếp."
    $ set_player_expression("confused")
    mc "Sao không hiện?"
    necrass_sim "Để ngươi sống trong lo âu."
    $ set_player_expression("smug")
    mc "Game design đỉnh cao."
    necrass_sim "Và giờ—"
    # [SFX] RING RING RING RING!!!
    $ play_scene_sound("alarm")
    # [BG] Phòng ngủ trở lại.
    scene bedroom_morning
    $ scene_ambience("room")
    $ set_stage("player")
    with Dissolve(0.3)
    $ set_player_expression("panic")
    mc "ỐI ZỜI ƠI!"
    # [ACT] MC bật dậy.
    $ set_player_expression("confused")
    mc "Mình vừa mơ cái quái gì vậy?!"
    # [ACT] Nhìn đồng hồ.
    $ set_player_expression("sleepy")
    mc "6:29…"
    mc "Còn sớm."
    pause 0.35
    $ set_player_expression("thinking")
    mc "…Hay ngủ thêm đúng năm phút?"
    system_msg "FIRST CHOICE"
    menu:
        "“Ngủ tiếp. Gặp lại nữ thần.”":
            $ change_energy(+5)
            $ overslept = True
            jump ch1_sleep_again
        "“Dậy ngay. Không ngu nữa.”":
            $ change_energy(0)
            $ responsible_once = True
            jump ch1_wake_up

label ch1_sleep_again:
    # [BG] Fantasy void.
    scene dream_place
    $ scene_ambience()
    $ set_stage("player", "necrass")
    with Dissolve(0.3)
    $ set_player_expression("goodmood")
    mc "Tôi quay lại rồi."
    necrass_sim "Ta biết."
    $ set_player_expression("smug")
    mc "Cho hỏi route romance của cô mở Chapter mấy?"
    necrass_sim "Không tồn tại."
    $ set_player_expression("annoyed")
    mc "Thế tôi ngủ tiếp làm gì?"
    necrass_sim "Đúng câu hỏi đấy."
    # [SFX] Chuông báo thức vang như còi báo động hạt nhân.
    $ play_scene_sound("alarm")
    # [BG] Phòng ngủ.
    scene bedroom_morning
    $ scene_ambience("room")
    $ set_stage("player")
    with Dissolve(0.3)
    $ set_player_expression("surprised")
    mc "…6:52?!"
    # [ACT] MC bật khỏi giường.
    $ set_player_expression("panic")
    mc "NĂM PHÚT CỦA AI ĐÂY?!"
    system_msg "Late Pressure unlocked."
    jump ch1_morning_prep

label ch1_wake_up:
    # [ACT] MC ngồi im trên giường 10 giây.
    $ set_player_expression("determined")
    mc "Được rồi."
    mc "Dậy."
    pause 0.35
    $ set_player_expression("sleepy")
    mc "…"
    mc "Chân, hợp tác nào."
    # [ACT] Không nhúc nhích.
    $ set_player_expression("annoyed")
    mc "Tao đang nói với hai đứa mày đó."
    system_msg "Nhân vật chính đã chiến thắng Boss đầu tiên: Cái giường."
    jump ch1_morning_prep

label ch1_morning_prep:
    # [BG] Góc bếp nhỏ / phòng trọ.
    scene bedroom_morning
    $ scene_ambience("room")
    $ set_energy_expression()
    $ set_stage("player")
    with Dissolve(0.3)
    # [ACT] MC nhìn đồ ăn sáng, balo và đồng hồ.
    menu:
        "Ăn sáng tử tế.":
            $ breakfast_eaten = True
            $ set_player_expression("goodmood")
            mc "“Có thực mới vực được… qua tiết đầu.”"
            $ change_energy(+15)
        "Uống cà phê thay cơm.":
            $ set_player_expression("smug")
            mc "“Đây không phải dinh dưỡng. Đây là kỹ thuật hồi sinh.”"
            $ change_energy(+8)
            $ coffee_only = True
        "Bỏ luôn, chạy đi học.":
            $ set_player_expression("determined")
            mc "“Ăn sáng là DLC.”"
            $ change_energy(-10)
    if overslept:
        system_msg "Bạn đang trễ."
        menu:
            "Chạy nước rút ra ngoài.":
                $ set_player_expression("panic")
                $ change_energy(-15)
            "Chấp nhận số phận, đi bình thường.":
                $ change_energy(-2)
                $ class_late = True
    $ player_is_on_campus = True
    $ infirmary_window_open = True
    jump ch1_arrival

label ch1_arrival:
    # [BG] Cổng campus buổi sáng. Sinh viên đi qua lại. Không quá đông. (FPTUGate.png)
    scene school_gate_morning
    $ scene_ambience("campus")
    $ set_energy_expression()
    $ set_stage("player", "minh")
    with Dissolve(0.3)
    # [ACT] Minh đứng cạnh máy bán nước, ăn mặc gọn và có gu hơn hẳn MC.
    m "Ồ."
    mc "Gì?"
    m "Mày còn sống."
    $ set_player_expression("annoyed")
    mc "Sáng sớm nói câu nghe xúi quẫy vậy, cha nội?"
    m "Thế tối qua ai bảo “ván này xong tao ngủ”?"
    $ set_player_expression("deadpan")
    mc "Tao."
    m "Ai bấm Ready tiếp?"
    mc "Cũng tao."
    m "Ai có tiết sáng?"
    mc "…"
    m "Tao thích cái cách mày tự xây boss fight cho chính mình."
    if class_late:
        m "Mà khoan… giờ này mới tới?"
        mc "Tao đang áp dụng chiến thuật “xuất hiện đúng lúc giảng viên bắt đầu điểm danh”."
        m "Mày gọi đó là chiến thuật?"
        $ set_player_expression("smug")
        mc "Risk management."
        m "Mày học Game Dev chứ có học tài chính đâu cu ơi!"
    menu:
        "“Mua tao chai nước đi, người anh em.”":
            m "“Tự mua.”"
            mc "“Tình bạn mỏng hơn ping Wi-Fi.”"
            $ change_energy(+3)
        "“Tối nay làm thêm vài ván?”":
            m "“Mày chưa học được gì cả.”"
            $ still_no_regret = True
        "“Tối nay tao ngủ sớm.”":
            $ set_player_expression("deadpan")
            m "“Tao sẽ ghi âm câu này lại và đóng nó cho viện bảo tàng Anh Quốc.”"
            $ fake_promise = True
    jump ch1_hallway

label ch1_hallway:
    # [BG] Hành lang lớp học. (HallwayFPTUDay.png)
    scene hallway
    $ scene_ambience("campus")
    $ set_energy_expression()
    $ set_stage("player", "minh", "linh")
    with Dissolve(0.3)
    # [ACT] Linh bước tới, ôm laptop và một tập tài liệu.
    l "Hai ông đứng chắn giữa đường làm gì vậy?"
    m "Tưởng niệm giấc ngủ của nó."
    $ set_player_expression("deadpan")
    mc "Nó hy sinh lúc 2 giờ sáng."
    l "Lại chơi game?"
    $ set_player_expression("smug")
    mc "Nghiên cứu thực nghiệm."
    l "Game nào?"
    $ set_player_expression("embarrassed")
    mc "…"
    l "Đấy. Biết ngay mà."
    # [ACT] Linh nhìn mặt MC.
    l "Ông ổn không đấy? Nhìn như vừa respawn lỗi texture."
    $ set_player_expression("smug")
    mc "Đây là vẻ đẹp tự nhiên của sinh viên gần năm cuối."
    l "Không. Đây definitely là thiếu ngủ."
    menu:
        "“Yên tâm, tôi khỏe.”":
            $ set_player_expression("goodmood")
            l "“Người sắp xỉu thường nói vậy.”"
        "“Có đồ ăn không?”":
            $ set_player_expression("sleepy")
            l "“Có sẵn thanh ngũ cốc nè. Xơi không?”"
            $ change_energy(+7)
        "“Nếu tôi ngã, nhớ save project trước.”":
            $ set_player_expression("smug")
            l "“Tôi save project. Ông tự save mình.”"
            $ change_trust("linh", +1)
    jump ch1_lab

label ch1_lab:
    # [BG] Phòng lab. Màn chiếu, PC, dây điện đủ loại. (ComputerLabDay.png)
    scene computer_lab
    $ scene_ambience("classroom")
    $ set_energy_expression()
    $ set_stage("player", "minh", "linh", "thaydev", visual=("player", "thaydev"))
    with Dissolve(0.3)
    # [SFX] Cửa mở.
    $ play_scene_sound("door")
    # [ACT] Thầy Dev bước vào, cắm laptop.
    dev "Chào các em."
    crowd "Dạ chào thầy."
    dev "Hôm nay chúng ta sẽ nói về kiến trúc hệ thống."
    # [ACT] MC ngồi thẳng lại.
    $ set_player_expression("serious")
    mc_thought "Được. Mình ổn. Chỉ cần tập trung."
    dev "Giả sử project của các em có tám scene, mười hai manager và ba script cùng tự nhận mình là GameManager—"
    $ set_player_expression("nervous")
    mc_thought "Thầy đang công kích cá nhân mình à?"
    minh_whisper "Mặt mày tái mét thế kia."
    $ set_player_expression("deadpan")
    mc_whisper "Tao thấy quá khứ huy hoàng."
    dev "Và đặc biệt, đừng để toàn bộ logic chạy trong một file ba nghìn dòng."
    # [ACT] MC từ từ cúi xuống bàn.
    linh_whisper "Trúng tim đen rồi à?"
    $ set_player_expression("deadpan")
    mc "Không."
    l "Ông vừa tắt màn hình laptop."
    mc "Nó cần được yên nghỉ."
    system_msg "TUTORIAL: ENERGY CHECKPOINT"
    if energy > 45:
        $ set_player_expression("serious")
        mc_thought "Mệt, nhưng vẫn xử lý được."
    elif energy >= 25:
        $ set_player_expression("sleepy")
        mc_thought "Não đang chạy 30 FPS."
    else:
        $ set_player_expression("exhaust")
        # [ACT] Chữ trên slide bắt đầu hơi nhòe.
        $ set_player_expression("exhaust")
        mc_thought "Tại sao cái Singleton Pattern đang… trôi?"
    dev "Các em có mười phút. Nhìn đoạn code này và chỉ ra vấn đề."
    menu:
        "Tự làm nghiêm túc.":
            $ set_player_expression("serious")
            $ change_energy(-8)
            $ dev_respect += +1
        "Trao đổi với Minh.":
            $ set_player_expression("normal")
            $ change_energy(-3)
        "Nhìn sang Linh với ánh mắt cầu cứu.":
            $ set_player_expression("nervous")
            l "“Đọc đi. Tôi gợi ý chứ không làm hộ đâu.”"
            $ change_energy(-2)
            $ change_trust("linh", +1)
        "Gục mặt 10 giây để “tối ưu CPU”.":
            $ set_player_expression("sleepy")
            $ change_energy(+4)
            $ lab_troll = renpy.random.random() < 0.30
            if lab_troll:
                $ set_player_expression("surprised")
                dev "Em kia."
                # [ACT] MC bật dậy.
                mc "Dạ em đang suy nghĩ."
                dev "Bằng mí mắt à?"
                $ set_player_expression("nervous")
                mc "Dạ… phương pháp mới."
                dev "Thế kết quả thì sao?"
                $ set_player_expression("deadpan")
                mc "Code có vấn đề ạ."
                dev "Thầy cũng có thể nhìn ra điều đó và cả em ở trỏng."
    jump ch1_break

label ch1_break:
    # [BG] Khu vực bàn ghế ngoài hành lang / cafeteria. (CanteenFPTUDay.png)
    scene canteen
    $ scene_ambience("canteen")
    $ set_energy_expression()
    $ set_stage("player", "minh", "linh", "ngan", visual=("player", "minh", "ngan"))
    with Dissolve(0.3)
    # [ACT] Ngân ngồi với laptop, tai nghe một bên. Cô đang nhìn một file thiết kế / tài liệu.
    m "Ngân kìa."
    mc "Ừ."
    m "Ừ là sao?"
    mc "Thì… Ngân kìa."
    m "Khả năng quan sát tuyệt vời."
    # [ACT] Ngân ngẩng lên.
    ngan "Hai người nói nhỏ mà đứng cách tôi hai mét thì vẫn nghe được nhé."
    mc "Chào."
    ngan "Chào."
    m "Nó hôm nay mới ngủ bốn tiếng."
    $ set_player_expression("annoyed")
    mc "Mày bán thông tin cá nhân nhanh vậy?"
    ngan "Nhìn mặt là biết gồi."
    $ set_player_expression("confused")
    mc "Sao sáng giờ ai cũng nói câu này vậy?"
    ngan "Vì mặt ông đang tự viết status."
    menu:
        "“Status gì?”":
            $ set_player_expression("confused")
            ngan "“Last seen alive: yesterday.”"
            $ change_trust("ngan", +1)
        "“Tôi vẫn đẹp trai mà.”":
            $ set_player_expression("smug")
            ngan "“Cái đó tôi không phụ trách xác minh.”"
            $ change_trust("ngan", +1)
        "“Cho tôi dựa bàn ngủ 5 phút.”":
            $ set_player_expression("sleepy")
            ngan "“Năm phút của ông có lịch sử không đáng tin lắm.”"
            $ change_energy(+5)
        "“Tôi đi mua nước. Ai uống gì không?”":
            $ set_player_expression("goodmood")
            $ change_energy(-3)
            $ change_trust("ngan", +1)
            $ change_trust("linh", +1)
            m "Tao—"
            mc "Mày tự mua."
            m "Tình bạn mỏng hơn ping Wi-Fi."
            $ set_player_expression("annoyed")
            mc "Đừng ăn cắp thoại của tao."
    call ch1_campus_checkpoint
    if _return:
        jump ch1_infirmary
    jump ch1_lunch

label ch1_campus_checkpoint:
    if not route_locked and update_day_route() == "INFIRMARY":
        $ energy_visible = False
        $ set_stage("player", "linh", "ngan")
        # [ACT] MC đứng dậy rồi khựng lại.
        # [SFX] Âm thanh môi trường nhỏ dần.
        $ scene_ambience()
        $ set_player_expression("exhaust")
        mc "Khoan…"
        l "Ông sao vậy?"
        mc "Hình như mặt đất muốn hôn tôi…"
        # [ACT] Camera nghiêng nhẹ.
        show layer master at faint_tilt
        $ set_player_expression("panic")
        mc "…đang update physics."
        ngan "Này—"
        # [ACT] MC gục xuống.
        scene black with fade
        $ set_stage()
        show layer master
        system_msg "ROUTE OVERRIDE"
        system_msg "SPECIAL ROUTE UNLOCKED: INFIRMARY"
        return True
    return False

label ch1_lunch:
    # [BG] Canteen.
    scene canteen
    $ scene_ambience("canteen")
    $ set_energy_expression()
    $ set_stage("player", "minh", "linh", "ngan", visual=("player", "linh", "ngan"))
    with Dissolve(0.3)
    m "Ăn gì?"
    mc "Thứ gì hồi Energy nhiều nhất."
    l "Ông nói như đang đang chơi game vậy."
    $ set_player_expression("smug")
    mc "Cuộc đời sẽ dễ hơn nếu đồ ăn có stat."
    ngan "Cơm: +20 Energy. Trà sữa: +5 morale, -30 nghìn."
    m "Mì cay: +10 Energy, +50 regret."
    mc "Đấy. Thiết kế hệ thống hoàn chỉnh rồi còn gì."
    menu:
        "Ăn một bữa tử tế.":
            $ change_energy(+20)
        "Ăn nhẹ cho nhanh.":
            $ change_energy(+10)
        "Bỏ bữa để làm task.":
            $ set_player_expression("determined")
            $ change_energy(-10)
            $ deadline_greed = True
        "Cà phê lần hai.":
            $ change_energy(+6)
            $ too_much_coffee = True
    if deadline_greed:
        l "Ông không ăn thật à?"
        mc "Deadline không chờ ai."
        l "Dạ dày cũng không."
        m "Hai tiếng nữa cái dạ dày của nó gửi notification. Đợi thêm xíu tao nghi thằng hôn mặt đất quá bây ạ..."
    call ch1_campus_checkpoint
    if _return:
        jump ch1_infirmary
    # [BG] Lớp học buổi chiều. (ClassroomAfternoon.png)
    scene classroom_afternoon
    $ scene_ambience("classroom")
    $ set_energy_expression()
    $ set_stage("player", "minh", "linh", "ngan", visual=("player", "minh", "linh"))
    with Dissolve(0.3)
    $ campus_period = "afternoon"
    n "Buổi chiều trôi qua theo cách rất sinh viên."
    # [ACT] Montage:
    $ set_shot("player", "minh")
    with Dissolve(0.2)
    pause 0.2
    $ set_shot("linh", "ngan")
    with Dissolve(0.2)
    pause 0.2
    $ set_shot("player")
    with Dissolve(0.15)
    pause 0.15
    $ change_energy(-10)
    $ set_energy_expression("fatigue")
    if too_much_coffee:
        $ set_player_expression("panic")
        mc_thought "Tim mình đang chạy ở 144Hz."
    if 16 <= energy <= 25:
        $ set_player_expression("exhaust")
        mc_thought "Mình có thể nghe thấy tiếng xung quanh… bằng tâm hồn.\nMình đạt tới... đỉnh cao loài người rồi sao?"
    call ch1_campus_checkpoint
    if _return:
        jump ch1_infirmary
    jump ch1_after_class

label ch1_after_class:
    $ infirmary_window_open = False
    # [BG] Sân trường / khu thể thao cuối chiều. (SportsGroundAfternoon.png)
    scene sports_afternoon
    $ scene_ambience("sports")
    $ set_energy_expression()
    $ set_stage("player", "minh", "linh", "ngan", visual=("player", "linh", "ngan"))
    with Dissolve(0.3)
    # [ACT] MC, Minh, Linh và Ngân đang đi ra.
    $ set_player_expression("goodmood" if energy > 30 else "exhaust" if energy <= 25 else "sleepy")
    mc "Cuối cùng."
    m "Về à?"
    mc "Về chớ."
    l "Không ghé đâu nữa nhé."
    mc "Chắc chắn rồi."
    ngan "Ông nói nghe đáng ngờ quá."
    # [SFX] Tiếng còi thể thao.
    $ play_scene_sound("whistle")
    $ set_player_expression("surprised")
    pe_offscreen "EM KIA!"
    # [ACT] Cả bốn đứng lại.
    $ set_player_expression("nervous")
    mc "Tại sao mỗi lần ai đó nói “em kia” tôi đều cảm thấy đó là mình?"
    # [ACT] Thầy thể dục bước vào khung hình. Thân hình cực kỳ săn chắc, da bóng dưới nắng chiều như được render bằng shader kim loại.
    $ set_player_expression("panic")
    $ set_stage()
    scene cg_pe_intro with Dissolve(0.35)
    $ unlock_chapter1_cg("pe_intro")
    n "Và rồi anh ta xuất hiện."
    n "Người đàn ông."
    n "Huyền thoại."
    n "Khối hợp kim đen bóng biết đi."
    scene sports_afternoon with Dissolve(0.25)
    $ scene_ambience("sports")
    $ set_stage("player", "minh", "linh", "ngan", "pe", visual=("player", "pe"))
    pe "Em!"
    $ set_player_expression("nervous")
    mc "Dạ…"
    pe "Có chơi thể thao không?"
    # [ACT] MC nhìn ba người còn lại.
    m "Đừng nhìn tao."
    l "Tự cứu mình đi."
    ngan "Chúc may mắn."
    $ set_player_expression("panic")
    mc "Phản bội tập thể nhanh vậy?!"
    menu:
        "“Dạ em không chơi môn nào hết.”":
            $ set_player_expression("nervous")
            pe "Không chơi càng tốt."
            $ set_player_expression("confused")
            mc "…Dạ?"
            pe "Thầy đang tuyển người mới."
            mc "Logic gì vậy thầy?"
            pe "Người chưa biết thì dễ đào tạo."
            $ pe_pressure += +1
        "“Dạ em còn deadline.”":
            $ set_player_expression("serious")
            pe "Deadline càng cần vận động."
            $ set_player_expression("annoyed")
            mc "Em tưởng deadline cần làm bài."
            pe "Thân khỏe thì code mới khỏe."
            $ set_player_expression("smug")
            mc "Code em compile bằng CPU chứ đâu bằng cơ ngực—"
            # [ACT] Minh bịt miệng MC.
            m "Nó mệt nên nói nhảm đó thầy."
            $ pe_pressure += +1
        "“Dạ em rất thích thể thao ạ.”":
            $ set_player_expression("goodmood")
            pe "Tốt!"
            # [ACT] Thầy đặt tay lên vai MC.
            pe "Vậy mai 5 giờ chiều ra sân."
            $ set_player_expression("panic")
            mc "Khoan—"
            $ pe_club_captured = True
        "Giả vờ nhận điện thoại rồi lùi dần.":
            $ set_player_expression("smug")
            # [ACT] MC lấy điện thoại ra.
            $ set_player_expression("smug")
            mc "Dạ alo? Cháy server hả? Tôi biết rồi, tới liền ngay!"
            m "…"
            l "…"
            ngan "…"
            mc "Dạ em tới ngay!"
            # [ACT] MC lùi một bước.
            pe "Điện thoại em đang ở màn hình khóa."
            pause 0.35
            $ set_player_expression("nervous")
            mc "Server gọi bằng thần giao cách cảm ạ."
            $ pe_pressure += +2
    if pe_club_captured:
        jump ch1_black_alloy_club
    if pe_pressure >= 2:
        pe "Thầy thích tinh thần của em."
        $ set_player_expression("confused")
        mc "Em có tinh thần gì đâu thầy?"
        pe "Tinh thần cần được rèn luyện."
        mc "Khoan, câu đó—"
        # [ACT] Thầy đưa tờ đăng ký CLB.
        system_msg "FINAL RESISTANCE CHOICE"
        menu:
            "Ký vì não đã hết pin.":
                $ pe_club_captured = True
            "Từ chối lịch sự lần cuối.":
                $ change_energy(-5)
                if energy > 20:
                    $ set_player_expression("serious")
                    mc "Dạ em cảm ơn thầy, nhưng lịch học và project của em hiện tại không cho phép. Khi nào ổn hơn em sẽ chủ động đăng ký sau ạ."
                    pause 0.35
                    pe "Ừ. Được. Thầy sẽ always welcome em nếu em có thể."
                    # [ACT] Thầy đi.
                    $ set_stage("player", "minh", "linh", "ngan", visual=("player", "linh", "ngan"))
                    with Dissolve(0.25)
                    # [ACT] Cả nhóm im lặng.
                    m "Ủa."
                    l "Ông vừa nói chuyện như người trưởng thành."
                    ngan "Ghi lại ngày này đi."
                    mc "OMFG...\nOk, tao sẽ ghi lại và gửi cho viện bảo tàng Anh Quốc."
                else:
                    $ set_player_expression("exhaust")
                    mc "Dạ… em cảm ơn thầy… hiện tại lịch em…"
                    # [ACT] MC đứng đơ.
                    pe "Lịch em sao?"
                    $ set_player_expression("deadpan")
                    mc "…trống."
                    $ set_player_expression("panic")
                    mc_thought "KHÔNG! NÃO ƠI! TAO LẠY MÀY NÃO ƠI!"
                    pe "Tuyệt vời."
                    $ pe_club_captured = True
    if pe_club_captured:
        jump ch1_black_alloy_club
    jump ch1_leaving_campus

label ch1_leaving_campus:
    # [BG] Cổng trường cuối chiều. (FPTUGateAfternoon.png)
    scene school_gate_afternoon
    $ scene_ambience("campus")
    $ set_stage("player", "minh", "linh", "ngan", visual=("player", "minh", "ngan"))
    with Dissolve(0.3)
    m "Tối nay game không?"
    $ set_player_expression("determined")
    mc "Không."
    m "Tao chưa nói game gì."
    mc "Không."
    l "Giỏi, có tiến bộ rồi đấy."
    ngan "Tao công nhận điều đó Linh ạ, ngày nay thằng này bị ai nhập à?\nNói chứ bye mai gặp nha, bạn hiền~"
    $ set_player_expression("goodmood" if energy > 30 else "exhaust")
    mc "Bye anh em, mai gặp."
    # [ACT] Cả nhóm tách ra.
    $ set_stage("player")
    with Dissolve(0.25)
    system_msg "FINAL ENERGY CHECK"
    $ update_day_route(end_of_day=True)
    $ player_is_on_campus = False
    $ energy_visible = False
    if current_route == "WALKING_CORPSE":
        jump ch1_walking_corpse
    jump ch1_home_safe

label ch1_home_safe:
    # [BG] Đường về nhà, hoàng hôn.
    scene homeward_sunset
    $ scene_ambience()
    $ set_stage("player")
    with Dissolve(0.3)
    n "Không bị kéo vào câu lạc bộ."
    n "Không gục giữa sân trường."
    n "Không phải tỉnh dậy dưới ánh đèn phòng y tế."
    n "Theo tiêu chuẩn sinh viên IT…"
    n "…đây là một ngày thành công ngoài mong đợi."
    # [BG] Phòng MC buổi tối.
    scene bedroom_gaming
    $ scene_ambience("room")
    $ set_stage("player")
    with Dissolve(0.3)
    # [ACT] MC quăng balo xuống ghế, ngồi xuống giường.
    $ set_player_expression("sleepy")
    mc "Mệt."
    # [ACT] Nhìn laptop.
    pause 0.35
    # [SFX] Discord notification.
    $ play_scene_sound("notification")
    minh_message "“Vui vẻ 1 xíu chứ :>>>>>>>?”"
    menu:
        "Tắt Discord.":
            $ set_player_expression("serious")
            mc "Không thể phạm cùng một sai lầm hai ngày liên tiếp."
            pause 0.35
            mc "…chắc vậy."
        "Nhìn tin nhắn 10 giây.":
            $ set_player_expression("thinking")
            mc "Đừng dụ tao."
        "Gõ “không” rồi xóa.":
            $ set_player_expression("smug")
            # [ACT] MC gõ “không”.
            # [ACT] Xóa.
            # [ACT] Gõ “mai”.
            mc "Đấy. Character development áp dụng trong 1 ngày."
    $ set_stage()
    scene cg_good_sleep with fade
    $ unlock_chapter1_cg("good_sleep")
    pause 0.5
    $ scene_ambience()
    scene dream_place with fade
    $ set_stage("player", "necrass")
    necrass "Thế là ta có thể tin tưởng cậu và hành trình sắp tới của cậu được rồi. Chàng trai trẻ!"
    $ set_player_expression("surprised")
    mc "Á đu- lại là cô nữa á? Lần này là gì nữa đây?"
    necrass "\"Cậu đã làm rất tốt, hành trình sau này của cậu còn đầy giang nan và khổ cực\nTa mong rằng cậu vẫn có thể giữ vững tinh thần và ý chí này\"\nĐó là lời của chồng ta nói vậy với cậu\nChứ không thì cậu vào bộ sưu tập thú vị của ta cùng mấy thằng đệ dưới trướng ta rồi."
    $ set_player_expression("deadpan")
    mc "......"
    necrass "Ta không còn gì để hướng dẫn hay nói thêm với cậu\nHành trình sau này sẽ do cậu, cứ từ từ mà tận hưởng~~~"
    n "Nhân vật kia biến mất trong giấc mơ của nhân vật chính chúng ta và\nthật bất ngờ là thằng nhân vật chính của chúng ta bị ai đó cho u sọ não\nNên sáng hôm sau nó gần như quên hết về nữ thần trong mơ gì đó của nó :>>>>>>"
    system_msg "CHAPTER 1 COMPLETE\nGOOD ROUTE: HOME SAFE"
    n "Ngày đầu tiên kết thúc.\nKhông có gì đặc biệt xảy ra."
    pause 0.35
    n "Tạm thời."
    jump ch1_end

label ch1_black_alloy_club:
    $ update_day_route(end_of_day=True)
    $ energy_visible = False
    # [BG] Sân thể thao. (SportsGroundAfternoon.png)
    scene sports_afternoon
    $ scene_ambience("sports")
    $ set_stage("player", "minh", "linh", "ngan", "pe", visual=("player", "pe"))
    with Dissolve(0.3)
    # [ACT] Thầy thể dục cười cực kỳ hài lòng.
    pe "Tốt! Mai 5 giờ chiều nhé em trai."
    $ set_player_expression("panic")
    mc "Thầy ơi em chưa—"
    pe "Thầy tin em."
    mc "Nhưng em không tin em!"
    # [ACT] Thầy vỗ vai MC.
    # [SFX] *BỐP.*
    $ play_scene_sound("pat")
    # [ACT] MC tụt nhẹ xuống vì lực vỗ.
    m "Xin chia buồn."
    l "Ông ổn không?"
    $ set_player_expression("deadpan")
    mc "Không."
    ngan "Nhìn mặt là biết."
    $ set_player_expression("sad")
    mc "Tôi vừa mất quyền tự quyết của đời mình."
    # [BG] Phòng MC tối hôm đó.
    scene bedroom_gaming
    $ scene_ambience("room")
    $ set_stage("player")
    with Dissolve(0.3)
    # [ACT] MC nhìn tờ đăng ký CLB trên bàn.
    $ set_player_expression("deadpan")
    mc "Mình đi học Game Dev."
    mc "Tại sao ngày đầu game lại unlock Fitness DLC?"
    # [SFX] Điện thoại báo tin nhắn.
    $ play_scene_sound("notification")
    pe_message "“Mai nhớ mang đồ thể thao em nhé 💪”"
    # [ACT] MC nằm vật xuống giường.
    $ set_player_expression("cry")
    mc "Hết."
    mc "Hết chuyện tình thời sinh viên."
    mc "Ngày mai tôi kết hôn với cơ bắp."
    system_msg "CHAPTER 1 COMPLETE\nBAD ROUTE: BLACK ALLOY CLUB"
    system_note "Bạn đã bị một khối hợp kim đen bóng tuyển dụng thành công."
    jump ch1_end

label ch1_walking_corpse:
    # [BG] Đường về lúc trời tối dần.
    scene homeward_dusk
    $ scene_ambience()
    $ set_stage("player")
    with Dissolve(0.3)
    # [ACT] MC đi rất chậm.
    $ set_player_expression("exhaust")
    mc_thought "Chỉ cần về tới nhà."
    mc_thought "Giường."
    mc_thought "Mình cần giường."
    # [SFX] Tin nhắn từ Minh.
    $ play_scene_sound("notification")
    minh_message "“Về chưa?”"
    # [ACT] MC nhìn màn hình.
    $ set_player_expression("deadpan")
    mc "Tao đang… loading."
    # [BG] Phòng MC.
    scene bedroom_gaming
    $ scene_ambience("room")
    $ set_stage("player")
    with Dissolve(0.3)
    # [ACT] Cửa mở.
    # [ACT] MC bước vào được hai bước.
    # [ACT] Balo rơi xuống trước.
    # [SFX] *Bịch.*
    $ play_scene_sound("bag")
    $ set_player_expression("exhaust")
    mc "Mai…"
    # [ACT] MC ngã xuống giường nguyên quần áo.
    mc "…nghỉ game…"
    pause 0.35
    mc "…chắc vậy…"
    # [ACT] Màn hình tối.
    $ set_stage()
    scene cg_walking_corpse with Dissolve(0.35)
    $ unlock_chapter1_cg("walking_corpse")
    pause 0.5
    scene black with fade
    n "Bạn không bị ngất ở trường."
    n "Bạn không gặp cô y tá."
    n "Bạn cũng không bị bắt vào CLB."
    n "Nhưng cơ thể bạn đã chính thức gửi đơn đình công."
    system_msg "CHAPTER 1 COMPLETE\nBAD ROUTE: WALKING CORPSE"
    system_note "Về được tới nhà với 1%% pin vẫn là về được tới nhà.\nNhưng game không tính đó là chiến thắng."
    jump ch1_end

label ch1_infirmary:
    $ scene_ambience()
    $ energy_visible = False
    # [BG] Màn hình đen.
    scene black
    $ scene_ambience()
    $ set_stage()
    with Dissolve(0.3)
    # [SFX] Tiếng quạt trần. Tiếng giấy lật.
    mc "…"
    $ set_player_expression("confused")
    mc "Mình chết rồi à?"
    nurse_voice "Nếu chết rồi thì em đang nói hơi nhiều đấy."
    # [ACT] MC mở mắt.
    scene cg_nurse_intro with Dissolve(0.35)
    $ unlock_chapter1_cg("nurse_intro")
    pause 0.5
    # [BG] Phòng y tế. (MedicalRoomDay.png)
    scene expression ('infirmary_afternoon' if campus_period == 'afternoon' else 'infirmary_morning')
    $ scene_ambience("infirmary")
    $ set_stage("player", "nurse")
    with Dissolve(0.3)
    # [ACT] Cô y tá ngồi bên cạnh, đang ghi gì đó.
    mc "À."
    $ set_player_expression("deadpan")
    mc "Respawn point."
    nurse "Phòng y tế."
    mc "Gần giống nhau ạ."
    nurse "Hôm qua em ngủ bao nhiêu tiếng?"
    $ set_player_expression("nervous")
    mc "Câu này có ảnh hưởng điểm không ạ?"
    nurse "Không. Mày nhảm rồi đó :>>>"
    mc "Khoảng… bốn."
    # [ACT] Cô y tá dừng bút.
    nurse "Ăn sáng?"
    if breakfast_eaten:
        mc "Có ạ."
        nurse "Ít nhất còn cứu được một điểm."
    elif coffee_only:
        mc "Em uống cà phê."
        nurse "Cô hỏi ăn sáng."
        $ set_player_expression("smug")
        mc "Cà phê là súp nâu nấu từ hạt."
        pause 0.35
        nurse "Không."
    else:
        $ set_player_expression("embarrassed")
        mc "…"
        nurse "Không ăn đúng không?"
        $ set_player_expression("confused")
        mc "Cô đọc suy nghĩ em à?"
        nurse "Chuyện thường ở huyện."
    # [ACT] Cô đưa nước cho MC.
    nurse "Uống đi. Nằm nghỉ thêm. Hôm nay đừng chạy đi đâu nữa."
    mc "Em còn—"
    nurse "Không."
    mc "Nhưng—"
    nurse "Không nhưng nhị."
    $ set_player_expression("nervous")
    mc "Em chưa nói gì mà."
    nurse "Cô biết em định nói gì."
    system_msg "ALL ACTIVE ROUTES FOR TODAY HAVE BEEN SUSPENDED."
    $ set_player_expression("confused")
    mc "Ủa?"
    nurse "Sao?"
    $ set_player_expression("deadpan")
    mc "Không có gì. Em vừa cảm giác tương lai mình bị khóa."
    # [ACT] Cô y tá nhìn MC như đang đánh giá liệu cậu có sốt hay không.
    nurse "Ngủ tiếp đi. Chưa nặng tới vậy đâu, bị mỗi tội thức quá nên nói xàm nhiều."
    mc "Dạ."
    # [BG] Chiều muộn. Ánh nắng đã dịu. (MedicalRoomAfternoon.png)
    scene infirmary_afternoon
    $ scene_ambience("infirmary")
    $ set_player_expression("normal")
    $ set_stage("player", "nurse")
    with Dissolve(0.3)
    # [ACT] MC tỉnh dậy.
    nurse "Đỡ chưa?"
    mc "Đỡ rồi ạ."
    nurse "Lần sau ngủ đủ, ăn đủ, uống nước đủ và bớt cái súp nâu đen trong ly dùm cô."
    mc "Dạ."
    nurse "Và đừng xem cơ thể mình như thanh stamina trong game. Đời không phải game nhá!"
    pause 0.35
    mc "…"
    nurse "Sao?"
    $ set_player_expression("empathy")
    mc "Không có gì ạ.\nEm cảm ơn cô nhiều."
    nurse "...\nUkm, về đi. Nhớ cô dặn đó!"
    system_msg "CHAPTER 1 COMPLETE\nSPECIAL ROUTE: INFIRMARY"
    system_note "Bạn không hoàn thành được bất cứ kế hoạch nào trong ngày.\nNhưng ít nhất bạn đã unlock một địa điểm mới."
    jump ch1_end

label ch1_end:
    $ finish_chapter1()
    $ scene_ambience()
    hide screen energy_hud
    call screen chapter1_end
    return
