# Use supplied filenames exactly, including MainSurpised.png's spelling.
# Height-based scaling keeps every cast member proportional and equally tall.
image player embarrassed = character_sprite("MainEmbarrassed.png")
image player empathy = character_sprite("MainEmpathy.png")
image player sad = character_sprite("MainSad.png")
image player surprised = character_sprite("MainSurpised.png")
image player very_happy = character_sprite("MainVeryHappy.png")
image ngan = character_sprite("NganNormal.png")
image ngan happy = character_sprite("NganHappy.png")
image ngan excited = character_sprite("NganWelcome.png")
image ngan sad = character_sprite("NganSad.png")
image ngan angry = character_sprite("NganAngry.png")
image ngan big_laugh = character_sprite("NganVeryHappyAndBigLaugh.png")
image ngan confused = character_sprite("NganAwkward.png")
image ngan thinking = character_sprite("NganThinking.png")
image ngan embarrassed = character_sprite("NganEmbarrassed.png")
image nghi = character_sprite("NghiNormal.png")
image nghi soft_smile = character_sprite("NghiSmile.png")
image nghi happy = character_sprite("NghiHappy.png")
image nghi confused = character_sprite("NghiThinking.png")
image nghi annoyed = character_sprite("NghiAngry.png")
image nghi sad = character_sprite("NghiSad.png")
image nghi embarrassed = character_sprite("NghiEmbarrassed.png")
image nghi relaxed = character_sprite("NghiNormal2.png")
# Teachers use the same height as students, without a smaller portrait frame.
image philosophy = character_sprite("MissPhilosophy.png")
image nurse = character_sprite("Nurse.png")
image pe = character_sprite("PhysicalTeacher.png")

define nghi = Character("NGHI", color="#f6e6b1", callback=partial(stage_speaker, "nghi"))
define ngan = Character("NGÂN", color="#94dcff", callback=partial(stage_speaker, "ngan"))
define philosophy = Character("CÔ TRIẾT", color="#ffb5b5", callback=partial(stage_speaker, "philosophy"))
define nurse = Character("CÔ Y TÁ", color="#bcf6d9", callback=partial(stage_speaker, "nurse"))
define pe = Character("THẦY THỂ DỤC", color="#ffd495", callback=partial(stage_speaker, "pe"))
# Phone messages are not physically present speakers.
define ngan_message = Character("NGÂN · TIN NHẮN", color="#94dcff", callback=partial(stage_speaker, None))

image philosophy_morning = Transform("images/backgrounds/PhilosophyClassroomDay.png", size=(1280, 720))
image philosophy_afternoon = Transform("images/backgrounds/PhilosophyClassroomAfternoon.png", size=(1280, 720))
image philosophy_night = Transform("images/backgrounds/PhilosophyClassroomNight.png", size=(1280, 720))
image sports_morning = Transform("images/backgrounds/SportsGroundDay.png", size=(1280, 720))
image sports_afternoon = Transform("images/backgrounds/SportsGroundAfternoon.png", size=(1280, 720))
image sports_night = Transform("images/backgrounds/SportsGroundNight.png", size=(1280, 720))
image infirmary_morning = Transform("images/backgrounds/MedicalRoomDay.png", size=(1280, 720))
image infirmary_afternoon = Transform("images/backgrounds/MedicalRoomAfternoon.png", size=(1280, 720))
image infirmary_night = Transform("images/backgrounds/MedicalRoomNight.png", size=(1280, 720))
image library_morning = Transform("images/backgrounds/LibraryDay.png", size=(1280, 720))
image library_afternoon = Transform("images/backgrounds/LibraryAfternoon.png", size=(1280, 720))
image library_night = Transform("images/backgrounds/LibraryNight.png", size=(1280, 720))
image rooftop_morning = Transform("images/backgrounds/RooftopDay.png", size=(1280, 720))
image rooftop_afternoon = Transform("images/backgrounds/RooftopAfternoon.png", size=(1280, 720))
image rooftop_night = Transform("images/backgrounds/RooftopNight.png", size=(1280, 720))
image nearby_pub_night = Transform("images/backgrounds/DrinkingSpot.png", size=(1280, 720))
image cg_nghi_good = Transform("images/backgrounds/GoodEndingChapter2.png", size=(1280, 720))
image cg_ngan = Transform("images/backgrounds/EasterEggEndingChapter2.png", size=(1280, 720))
